pantavisor/pantavisor

- bootloader.c
- ctrl.c
- storage.c
- storage.h
- uboot.c
This refactor contains improvements for securely loading bootloader env files. These improvements have been made following these two premises:
* set limits to revision names to 64 bytes max
* use fixed buffer sizes of 1024 bytes to read from bootloader env files
Detailed list of changes:
* bootloader: refactor early init to use constants for cmdline buffer read
* bootloader: fixed one memory leak that could happen when cmdline read went bad
* ctrl: limit the size of all HTTP requests to avoid memory usage flood
* storage: limit the size of revision names to avoid memory usage flood
* uboot: use fixed size buffers to read from uboot.txt file
* uboot: use dynamic buffer allocation to better fit the needs depending on boot env file being in MTD or default
> refactor: improve protection of bootloader env file loading

- atom.mk
- buffer.c
- buffer.h
- log.c
- metadata.c
- ph_logger/ph_logger.c
At the current state, the log_buffer is used for logs and parsing metadata. Since the buffer is a general-purpose buffer, splitting the buffer from log should make the code cleaner.
> refactor: split buffer module out of log module

- scripts/volmount/dm
- state.c
make volmount handler 'novalidatelist' pluggable by running all executables in /pv/lib/volmount/ directory to gather the complete no validate list
> make volmount handler 'novalidatelist' pluggable

- atom.mk
- bootloader.c
- config_parser.c
- ctrl.c
- log.c
- metadata.c
- objects.c
- ph_logger/ph_logger.c
- plugins/pv_lxc.c
- pvlogger.c
- storage.c
- storage.h
- updater.c
- utils/file.c
- utils/file.h
- utils/system.c
This change gets pv-ctrl socket back to non-mgmt containers. Besides that, it checks the sender container privileges to discriminate all requests coming from non-mgmt containers. In the future, some requests will be allowed to non-mgmt, such as the condition requests.
* ctrl: new functions to return OK and CONT
* ctrl: new functions to get the container that is sending a new request
* ctrl: check sender platform privileges (mgmt or not) when a new request arrives
* ctrl: refactor pv_ctrl_process_endpoint_and_reply to make replies easier to follow
* ctrl: forbid legacy non-HTTP commands for non-mgmt
* ctrl: forbid all existing HTTP requests for non-mgmt
* ctrl: return 403 Forbidden when the request is not available for the requesting container
* pv_lxc: bind mount pv-ctrl …
> open pv-ctrl for non-mgmt platforms; forbid all existing request to non-mgmt plats

- log.c
- pantahub.c
- ph_logger/ph_logger.c
- updater.c
Update use of thttp and trest APIs with the new changes, which are mainly:
* remove all headers and queries arguments from trest requests. Shouldn't have any effect as we were setting those to 0 in all instances
* use thttp method enum instead of removed trest method enum for duplicity reasons
* use new thttp funciton to add headers instead of tampering with thttp struct to do so
> use new thttp and trest interfaces to solve double bearer bug

- atom.mk
- condition.c
- condition.h
- ctrl.c
- group.c
- group.h
- init.c
- init.h
- jsons.c
- jsons.h
- loop.c
- metadata.c
- objects.c
- objects.h
- pantavisor.c
- parser/parser_multi1.c
- parser/parser_system1.c
- platforms.c
- platforms.h
- plugins/pv_lxc.c
- state.c
- state.h
- storage.c
- updater.c
- updater.h
- volumes.c
- volumes.h
This change is about substituting runlevel by platform groups with conditions. Groups will allow to group platforms together, while conditions will affect the start order of plaforms. Instead of starting all of them in a row, Pantavisor will now check if the platform group conditions are met before that, and will block any platform until conditions are validated. To do so, Pantavisor will start platforms and mount their related volumes during WAIT state.
In this PR:
* condition: new module to define a structure that represent a condition
* condition: functions to alloc and free struct
* condition: functions to set value, check and get json
* condition: functions to allo and free references of the condition struct
* ctrl: new endpoints for containers and conditions
* ctrl: refactor …
> introduce platform groups and conditions

- state.c
- volumes.c
firmware and modules volumes were not being mounted from /trails to /volumes before being bind mounted from /volumes to /lib/firmware and /lib/modules. Regression caused by https://github.com/pantavisor/pantavisor/pull/29
> fix: modules and firware not being mounted

- ctrl.c
- signature.c
- storage.c
- storage.h
- updater.c
This MR makes pv-ctrl steps put to return an error if signature or format validation of the json goes wrong.
* ctrl: objects put wrong checksum returns now a 422 error
* ctrl: steps put wrong signature or format returns now a 422 error
* storate: new function to check signature and format of a stored revision
> add signature and format validation during step put

- condition.c
- condition.h
- group.c
- group.h
- parser/parser_system1.c
- platforms.c
- platforms.h
- state.c
- state.h
This PR allows for platforms to report their status changes as conditions. It also introduces default conditions between groups (old runlevels) so they are started in order depending on conditions
* condition: add platform field to struct
* group: remove condition refs as conditions are no longer attached to groups
* parser: parse container field in conditions and set * as default when not explicitly defined
* parser: remove unused function to parse group conditions
* platforms: status in now modified in one function that reports changes as conditions
* platforms: fix platform json regression introduced with the deletion of group.json
* platform: remove checking of group condition references
* state: fetch conditions with platform
* state: remove transfer of group …
> Status conditions

- config.c
- config.h
- pantavisor.c
- platforms.c
- state.c
- state.h
This PR adds rollback to the local experience
* config: new updater.conditions.timeout int configuration key
* pantavisor: add timer for conditions timeout
* pantavisor: rollback if conditions timeout timer times out before all current state conditions are satisfied
* platforms: only report status condition when a change in the status has occured
* state: new function to check if all state conditions are met
* general: improve logs when starting and mounting plats and vols
> rollback if any condition is not met when rollback timer times out

- scripts/volmount/crypt
Use losetup -f to find next free loop device
> Fix loop device starvation in crypt disk setup

- parser/parser_system1.c
- signature.c
- state.c
- updater.c
This change removes the files under _sigs/ to be considered in the reboot during an update transition. From now on, files in _sigs/ will only be considered for the signature verification, which is done independently in these places:
* after a reboot and before the current JSON state is parsed
* after downloading a new JSON state from remote and before is parsed
* before installing a new revision using pv-ctrl
* before running a revision using pv-ctrl
* before running the factory revision using pv-ctrl
List of detailed changes:
* parser: ignore _sigs/ files when parsing a JSON state
* signature: fix some log traces
* state: avoid crashes when fetching for objects, jsons, conditions, etc with NULL names
* updater: fix crash when json was not present after a pvcontrol commands run
> ignore _sigs when considering if reboot is necessary during update

- ctrl.c
- storage.c
- storage.h
* ctrl: return 507 when trying to PUT an object that is bigger than the free space available
* ctrl: fix one error that was making any PUT or POST method to get a content-length from HTTP headers bigger than what was actually in the headers
* storage: improve disk usage info in logs and add real and reserved disk space to devmeta
> return 507 insufficient space error when trying to put an object

- config.c
- ctrl.c
- pantahub.c
- pantavisor.c
- paths.c
- paths.h
- ph_logger/ph_logger_v1.c
- storage.c
- storage.h
- updater.c
- utils/file.c
- utils/file.h
- utils/fs.c
- utils/fs.h
- volumes.c
The idea is to use temporary files and sync when writing anything in disk. That way we want to avoid problems that could appear, specially with low disk throughput.
* config: use new pv_paths_tmp and pv_file_rename for saving pantahub.config
* crtl: use new pv_paths_tmp and pv_file_rename for putting files
* pantahub: use new pv_file_save for saving device-id and challenge
* pantavisor: use new pv_file_save for creating challenge
* paths: new function for tmp paths
* storage: use new pv_file_save and pv_file_copy for saving various storage files
* storage: remove unused tryonce and objdir functions
* updater: se new pv_paths_tmp and pv_file_rename for saving objects and state json
* utils/file: new functions to save and copy files. Using tmp files and sync
* volumes: use …
> refactor all file writing except bootloader ones to use tmp files and sync

- platforms.c
- plugins/pv_lxc.c
- plugins/pv_lxc.h
add usermeta_plat_key path function to callback set function to avoid undefined behaviour in non-mgmt platforms
> fix usrmeta_plat_key path function in callback set of pv_lxc

- config.c
- config.h
- init.c
- init.h
- pantavisor.c
- paths.c
- paths.h
- utils/json.c
* config: new config keys for paths taking /storage as example (/lib, /etc, /pv, /media, /configs)
* config: new config keys for debug (shell, ssh)
* config: new config keys for init mode (embedded, standalone and appengine)
* init: get config out of rest of early init so we can do it separatedly and use the init mode, paths and debug from it
* init: add --help with usage info of command
* paths: integrate new configurable paths
> prefix paths and init mode in config

- bootloader.c
- config.c
- config_parser.c
- ctrl.c
- init.c
- metadata.c
- mount.c
- pantavisor.c
- pantavisor.h
- parser/parser.c
- parser/parser.h
- parser/parser_multi1.c
- parser/parser_multi1.h
- parser/parser_system1.c
- parser/parser_system1.h
- paths.c
- paths.h
- ph_logger/ph_logger.c
- platforms.c
- plugins/pv_lxc.c
- state.c
- state.h
- storage.c
- updater.c
This change introduces the changes that are necessary to make apengine init mode work. This init mode allows to run Pantavisor in an existing Linux distro.
It is set in pantavisor.config like:
```
system.init.mode=appengine
```
With this, Pantavisor will expect state JSONs with the pantavisor-service-system@1 spec, but will not allow the bsp keys in them. 
* bootloader: get cmdline from pv struct instead of from disk
* config: fix value string override
* config: fix keep_factory
* config: move log.dir to pantavisor.config
* config_parser: get cmdline from pv struct instead of from disk
* ctrl: unlink socket after closing it to allow reopening
* init: avoid early mounts in appengine init mode
* init: allow cmdline as an argument. Load from disk if argument not used
* …
> appengine init mode

- atom.mk
- config.c
- config.h
- ctrl.c
- drivers.c
- drivers.h
- metadata.c
- metadata.h
- parser/parser_system1.c
- platforms.c
- platforms.h
- scripts/hooks_lxc-mount.d/mdev.sh
- state.c
- state.h
- utils/str.c
- utils/str.h
This adds support to a declarative interface in the BSP JSON
for kernel modules that are provided by the BSP and that expose
the said modules to the application containers depending on the
presence of a named dtb or dtbo object as passed by the bootloader.
> Declarative kernel module loading support for BSPs

- config.c
- config.h
- ctrl.c
- metadata.c
- metadata.h
- mount.c
- pantavisor.c
- paths.c
- paths.h
- platforms.c
- plugins/pv_lxc.c
- plugins/pv_lxc.h
- storage.c
- storage.h
This allows devmeta to be saved on disk and loaded after reboots in a usrmeta fashion. It also adds new pvctrl requests to save and delete devmeta (for now it requires mgmt role).
* config: deprecate meta.cache.dir in favour of cache.usrmetadir
* config: add new cache.devmetadir pantavisor.config key
* ctrl: add new PUT and DELETE usrmeta requests
* metadata: avoid initializating user-meta.<plat> if there is nothing to store
* metadata: save devmeta in storage when added
* metadata: add new rm devmeta function
* metadata: load devmeta from storage when initializing pv
* mount: mount new device-meta dir in /pv
* paths: new path functions for /storage and /pv devmeta
* pv_lxc: mount /storage/device-meta in mgmt plats
* pv_lxc: mount /storage/device-meta.<plat> in non-mgmt …
> add devmeta to storage and allow pvctrl management

- utils/filesystem.c
- utils/filesystem.h
This is the first of three PR to complete refactor the code present on `utils/fs.h` and `utils/file.h`
This PR adds `utils/filesystem.h` with all functions to replace the current implementations.
Next step:
1. Replace library calls
2. Delete the old libraries
> Refactor file and fs libraries

- metadata.c
- utils/str.c
- utils/str.h
Some change was added to this PR:
- Add better function to unescape chars and replace the old `pv_str_unescape_to_ascii` from `utils/str.h`
- Change the strategy of how user-meta is unescaped, now the data is unescaped after parsing
Both changes help to fix a nasty bug I found if you create a variable with any name but with the value `ooo\nooo` (something with a `\n` in between) the device will freeze completely.
> fix: usermeta does not unescape all special characters 

- config.c
- config.h
- metadata.c
- metadata.h
Add "metadata.devmeta.interval" to allow set the device meta timer
> Add timer to avoid hit pantahub every second with device meta

- scripts/volmount/crypt/crypt
- volumes.c
crypt failures with CAAM are sporadic and no meaningful debug information available with existing state. Adapt volume handler and add additional debug logs in error exit path.
> Fix: crypt logging

- storage.c
This toogle will make pantavisor skip checksumming all artifacts on boot time
> add support for pv_quickboot=1 cmdline toggle

- parser/parser_system1.c
- storage.c
- utils/str.h
We skip expanding those .json files then accordingly.
Introduce a helper function for pv_is_sha256_hex_string
> support shipping .json files in state json as objects

- parser/parser_system1.c
- platforms.c
- platforms.h
- state.c
This PR adds restart_policy to containers in run.json, which can be set to 'system' or 'container' to perform a full board reboot or a individual container reset. This value will override the previous behavior if any object or json is modified during an update, but it preserves the old behavior based on groups when not explicitly defined.
* parser: add restart_policy to run.json with 'system' and 'container' options
* platform: struct now stores restart_policy
* platform: json for pvcontrol now shows restart_policy value
* state: set 'system' default restart_policy if not explicitly configured for data, root and platform containers
* state: set 'container' default restart_policy if not explicitly configured for app containers
* state: decide whether to reboot or not for …
> add configurable restart_policy at container level in run.json

- init.c
- init.h
- log.c
- log.h
- logserver.c
- mount.c
- mount.h
- pantavisor.c
- ph_logger.c
- ph_logger.h
- state.c
- state.h
- storage.c
- storage.h
- utils/system.c
Add umounts to shutdown to free up the paths we are using after execution in appengine. The shutdown function has changed too to issue a lenient kill to the platform and ph logger forks first and then check if they are still running and finally send a force kill.
* init: new function to umount /writable and /exports
* logs: new function to umount logs in /pv
* logserver: modiy stop function to check if pid is still running after a timeout and issue a force kill if necessary
* mount: new function to umount devemta, usermeta and dropbear in /pv
* pantavisor: shutdown now issues lenient stop for ph logger and platforms at the same time. Then, check and force are sent if needed
* pantavisor: shutdown now umounts everything beyond /storage
* pantavisor: shutdown does not …
> refactor shutdown to be faster and add umounts

- config.c
- log.c
Move most of log keys in pantahub.config to pantavisor.config that are related to logserver but not to pantahub interaction at all. The old log keys in pantahub.config are still supported to keep backwards compatibility.
> deprecate some of the log keys in ph config in favour of pv config

- config.c
- config.h
- ctrl.c
- group.c
- group.h
- pantavisor.c
- parser/parser_multi1.c
- parser/parser_system1.c
- platforms.c
- platforms.h
- state.c
- state.h
- utils/json.h
This PR adds status_goal to the platform level configuration that substitutes the conditions feature.
* config: change updater.conditions.timeout with updater.goals.timeout
* ctrl: add GET /groups to list groups and status goals
* ctrl: add POST /signal to send ready signals
* ctrl: remove GET and PUT /conditions
* group: add list of platform refs for convinience
* group: check goals
* group: json function for pvcontrol
* pantavisor: switch condition rollback timer with goal one
* parser: remove condition parsing from run.json
* parser: add status_goal parsing from run.json
* platforms: substittue old READY status with INSTALLED
* platforms: add new READY status
* platforms: remove condition reporting when changing status
* platforms: remove list of condition refs
* …
> add configurable status_goal at container level in run.json

- atom.mk
- config.c
- utils/json-build/README.md
- utils/json-build/json-build.h
- utils/json.c
- utils/json.h
- utils/json.test.c
A memory leak in json-build library was causing realloc of json_ser buffers to crash. Besides fixing that, this MR also updates the library to latest master and improves utils/json.
* atom: add utils/json.test.c
* config: bring back the previously crashing 512 B initial buffer to pvcontrol config ls
* utils/json-build: update library to latest master
* utils/json-build: fix _jsonb_escape mem leak
* utils/json: port the while and resize check to all json_ser functions
* utils/json: improve resize functionnot to overwrite if realloc fails
* utils/json: use size_t for sizes in struct
* utils/json.test: test if resizing works
> fix: json-build mem leak and update library

- utils/json-build/json-build.h
This is not our fix for this problem, which was already merged to master. It is the upstream fix.
> fix: get upstream json-build resize mem leak fix

- bootloader.c
- bootloader.h
- config.c
- config.h
- logserver.c
- logserver.h
- pantavisor.c
* dont stop logserver on transition (we always accept logs)
* send USR1 signal on transition to logserver
* logserver rereads revision from bootloader pv_try on usr1 signal
* implement pv_bootloader_reload_pv_try in bootloader.c accordingly
* add LOG_SERVER_OUTPUT_NULL_SINK
* don't run pv_logserver_stop in pv_logserver_toggle
* don't run pv_logserver_toggle in _wait_network
> fix logserver not transitioning logs to new revision on no reboot update

- group.c
- parser/parser_system1.c
- state.c
Platforms were added to groups like this 
```
(*bundle->platform)->group = g;
pv_group_add_platform(g, (*bundle->platform));
```
So, first link the group to the platform, then call pv_group_add_platform, which links a platform reference to the group.
This was not being done in non-reboot transitions, were we skipped the second part. This was causing new states to have groups with references to the old revisions.
In this PR we put everything inside pv_group_add_platform and we call that one in every case. This needs an extra step, which is removing the current reference of the platform in the group.
> fix: platforms not properly transfered to new state groups in non-reboot transitions

- group.c
- group.h
- state.c
Currently, in non-reboot transitions, Pantavisor keeps the current state running for the new revision, but transfers the new/updated platforms from the pending state to the running one.This does not affect groups, as they are not changed whatsoever during non-reboot updates. We still have to re-link the platform reference list from the pending state to the current one.
Before this fix, Pantavisor was just re-linking the platforms belonging to the new revision, but the old ones belonging to platforms that were deleted or platforms that were modified were still there. This was causing Pantavisor to keep groups with lists of platform references that pointed to deleted structs etc.
With this fix, the list of references for each group are deleted during transitions, so the platforms belonging …
> fix: groups not cleaning old platform references during non-reboot transitions

- atom.mk
- defaults/groups.json
- group.c
- group.h
- parser/parser_system1.c
- paths.h
- platforms.c
- platforms.h
- state.c
- state.h
This PR introduces groups.json that permits to override the default groups (data, root, platform and app). New groups have a default restart policy and default status goal. However, those will be overloaded if explicitly configured at container level.
* group: add default status goal and default restart policy to struct
* parser: parse groups.json in state, which is an array of groups with name, status goal and restart policy
* parser: default groups are taken from initrd rootfs if groups.json is not present
* state: avoid creating default groups, which is parser's responsibility now
* state: add default status goal and restart policy to default groups
* state: post-parse validation now checks if any platform does not have a group attached, in case of non-default groups …
> groups.json

- config.c
- config.h
- metadata.c
- metadata.h
- pantavisor.c
Right now, all network operations updater.interval are performed at least in less than updater.interval seconds. This mainly includes:
* check if there is no ph connection and rollback if it times out
* check if connection is not stable during testing and rolback
* turn on/off ph logger depending on config
* send dev meta to ph
* receive user meta from ph
* check ph for new updates
These operations are not performed if updater.timer is timed out. In the case of the rollbacks, they won't be performed if the rollback or commit timer are less than the updater interval.
With this PR, all network operations are evaluated every second. Furthermore, sending dev meta, receiving usr meta and checking ph for updates depend on its own timers.
> fix: updater interval preventing other network operations

- ctrl.c
- logserver.c
- logserver.h
- pantavisor.c
- ph_logger.c
A bunch of small changes I did while testing appengine shuts down before WAIT state is reached. List of changes:
* ctrl: unlink before binding to remove existing pv-ctrl sockets
* logserver: merge close and stop functions
* logserver: add fd closing before stopping the PID, which was causing a freeze
* pantavisor: stop logserver after we stop ph_logger, platforms and pvctrl, but before unmount and free up memory
* ph_logger: improve logs when stopping services
> close logserver fds before killing its pid

- logserver.c
Fix missing LF on logs from /var/log
> Fix missing LF on /var/log logs

- parser/parser_system1.c
- state.c
- state.h
The idea behind this patch is to set all group-less platforms to a default one when groups.json is present in the revision. This default group will be the last configured group in groups.json
> add default group to group-less platforms when groups.json exist

- ctrl.c
- pantavisor.c
- pantavisor.h
- plugins/pv_lxc.c
- utils/system.c
- utils/system.h
cgroup version is now detected when initializing pantavisor. Based on the /sys/fs/cgroup/ file type and /sys/fs/cgroup/unified/, we determine if the system has the v1, the unified or the v2.
This information is then used from ctrl so sender platform name can be get from v2. It is also used in lxc plugin to substitute lxc.cgroup.devices.allow = a with lxc.cgroup2.devices.allow = a
> cgroup version detection

- config.c
- config.h
- log.c
- log.h
- logserver.c
- Removes log_to_consoles from log.c
- Add stdout output in config
- Make `log.stdout` working with Logserver
> Implement stdout as a logserver's sink

- config.c
- config_parser.c
- config_parser.h
* Allow set values from pantavisor.config using the following format: `sysctl.$prefix.$key=$value`
* Allow set values from cmdline (and overwrite those set on pantavisor.config) using `pv_sysctl.$prefix.$key=$value`
> Allow to set /proc/sys from pantavisor.config and cmdline

- scripts/volmount/crypt/crypt
- volumes.c
1. we will move to explicit .init_done marker file that we only place if whole do_crypt_init function has succeeded with changes synched to disk
2. we only do losetup logic for dm_type caam
3. we create a .goodbak copy of the image file every time we successfully finish with do_mount_disk; we are extra careful and create a .prebak copy of the image file before the mounting happens.
4. we make do_mount_disk try the following before giving up: - mount crypt disk as usual - if fails run an fsk.ext4 -y on that /dev/mapper/ device - if that fails we put back the .goodbak file (if such exist) at code we do this through recursive invocation of the do_mount_disk function with a 4th parameter 'specialrun' mode
> improve scripts/volmount/crypt/crypt to be more robust against corruption

- logserver.c
- utils/fs.c
* Add function to remove and unsubscribe fds (logserver_remove_fd)
* Add error handling to catch bad fds on epoll
* Add error handling to remove bad on read functions
* Replace calls to close fds with logserver_remove_fd
* Fix unsubscription mechanism adding a new header to subscribe or unsubscribe
> Add error handling to avoid problems with closed o bad fds

- logserver.c
- logserver.h
- pantavisor.c
- state.c
- volumes.c
- volumes.h
- wdt.c
* unmount disks
* degrade logs instead of killing; log to stdout after umount of /storage
* reboot at last possible moment with just logserver running
* improve error return code for pv_state_stop_force
* manually kick wdt after setting timeout
> make clean shutdown

- config.c
- config.h
- logserver.c
* Add `log.capture.dmesg` to activate or deactivate (1 or 0) this feature
* Add a fd from `/dev/kmsg` to logserver subscription
> Add dmesg on pantavisor log

- ctrl.c
- grub.c
- init.c
- metadata.c
- pantahub.c
- storage.c
- uboot.c
- updater.c
Another revision round of the missing sync through the code. In this case, the criteria has been:
* make sure we are using pv_fs_path_sync before closing an fd that was opened with writing permissions
* replace remove syscall with pv_fs_path_remove that uses pv_fs_path_sync internally
* make sure we are using pv_fs_path_rename that uses pv_fs_path_sync internally instead of rename syscall
* avoid closing unopened fds
> sync after every open with write permissions; use utils/fs remove

- config.c
- config.h
- log.c
- paths.c
- paths.h
Pantavisor can now load different policies at boot time. A policy is a configuration file following the same format as pantavisor.config. The files are located in /etc/pantavisor/policies/, so they can be added to each platform from vendor/stepskel/etc/pantavisor/policies/. The policy is set in the first stages of configuration (pantavisor.config or cmdline) and then loaded before the latest stages (initrdconfig or metadata config).
For example, if we wanted to load this policy from vendor:
```
vendor/stepskel/etc/pantavisor/policies/prod.config
```
We would have to set this key in cmdline:
```
pv_policy=prod
```
Another thing that would work is to set it in pantavisor.config
```
policy=prod
```
* config: add new "policy" key to pantavisor.config, overridable with pv_ …
> load config policies after pantavisor.config

- init.c
- uboot.c
This PR modifies uboot code so we set an empty var when unseting (only used for pv_rev=). It also fixes ssh activation, which was being set to true when the arg "splash" was not present. Now, besides being configurable, one can enable debug ssh and shell with the "pv_debug" arg.
> set empty uboot var in boot.txt instead of deleting it; fix ssh enabling

- config.c
- config.h
- log.c
This PR moves the loading of pantahub.config out of the early init so we can decide whether to load it or not based on Pantavisor being in remote or local mode. The idea is to only load the config file after bootup or transition once. Then, it is saved only after registration.
Because of this, devices might not load pantahub.config when in local mode, so we need to move the deprecated keys from pantahub.config to pantavisor.config to make this change complete.
* config: stop supporting deprecated pantahub.config keys
* config: print all config keys after log is initialized
* config: avoid loading pantahub.config on early init if remote is off
* config: improve logs for load/save pantahub.config
* log: move config print to config
> avoid loading pantahub.config in local mode; stop supporting deprecated ph.config keys

- log.c
- ph_logger.c
- pvlogger.c
- utils/fs.c
- utils/fs.h
Replace functions to set and get xattr from utils/fs with setxattr and getxattr
The functions on utils/fs try to mimic a behavior already present on the standard function, so they were replaced
> Fix ph_logger behavior

- metadata.c
- metadata.h
- mount.c
- pantavisor.c
So we can configure metadata mountings from the state JSON
> refactor: move metadata mounting out of early init

- init.c
- metadata.c
- metadata.h
- pantavisor.c
- parser/parser_system1.c
- paths.h
- state.c
- volumes.c
This PR allows metadata in crypt disks. The first thing that was needed for this change was to allow to set volumes in device.json. Having that, we can do a configuration like this:
```
"disks": [
{
"name": "dm-internal-secrets",
"path": "/storage/dm-crypt-files/dm-internal-secrets/versatile.img,2,versatile_key-internal_secrets",
"type": "dm-crypt-versatile"
}
],
"volumes": {
"pv--usrmeta": {
"disk": "dm-internal-secrets",
"persistence": "permanent"
},
"pv--devmeta": {
"disk": "dm-internal-secrets",
"persistence": "permanent"
}
}
```
Pantavisor will then check if pv--usrmeta and/or pv--devmeta are known volumes. If true, the volumes will be mounted on /pv/user-meta and /pv/dev-meta. If not true, the old behavior will follow, just mounting /storage/cache into /pv.
* init: …
> add volumes to device.json; allow metadata in volume

- group.c
- group.h
- pantavisor.c
- state.c
- state.h
Now group timers start only after each group finish its start process, that's mean that each group has the complete timeout to start.
> Fix timer start

- group.c
- group.h
- pantavisor.c
- platforms.c
- platforms.h
- state.c
- state.h
This refactor encapsulates the functionality of timeouts in the platform module. It also prepares the way for state status.
> refactor: move status goal timeout from groups into platform struct

- platforms.c
So we avoid returning TIMEDOUT on uninitialized timers
> fix: return UNACHIEVED always when a platform is in INSTALLED or BLOCKED status

- logserver.c
- utils/fs.c
Remove the extra LF present in some lxc (console.log and lxc.conf) logs
> Remove extra LF from lxc logs

- plugins/pv_lxc.c
Add origin=mkdir to lxc mounts to avoid situations in which the container start fails because of non existing origin directories.
> fix: lxc plugin not creating origin when trying to mount unexisting dirs

- paths.h
- storage.c
This is subsituted by creating a file /storage/config/mounted after mounting /storage. That file is then checked before getting storage info for GC and logs.
> fix: gc checking if pantahub.config exists

- config.c
- config.h
- pantahub.c
- pantavisor.c
This PR fixes a regression introduced with the pantahub.config only in non-remote patch. With this change, the load/saves are like this:
1. pantahub.config is always loaded if remote=1
2. if pantahub.config does not contain the credentials, try to load unclaimed.config
3. if unclaimed.config does not contain the credentials, try to register, save to unclaimed.config after registering
4. if unclaimed.config contains the credentials, try to claim, save to pantahub.config after claiming
> fix: pantavisor trying to load unexisting unclaimed.config

- atom.mk
- config.c
- debug.c
- debug.h
- init.c
- pantavisor.c
- volumes.c
This PR introduces "debug.ssh" to user meta, so dropbear can be started and stopped on run time. It also refactors all debug code to debug.h and debug.c.
* config: override debug.ssh from step config and user-meta
* debug: module with ssh and shell code
* debug: store pids for dropbear and shell session
* debug: functions to start and wait for shell
* debug: functions to start, stop and toggle ssh
* init: all debug related code moved to debug module
* pantavisor: all debug related code moved to debug module
> feature: disable/enable ssh server through user-meta

- log.c
- logserver.c
- pantavisor.c
- volumes.c
Logserver pid being killed after the socket closing was causing an error while closing, because they were still in use. The order of shutting down logserver has been rearranged so we first close sockets, then kill pids, then unmount stuff.
Besides that, we also have changed the unmounting of firmware and modules so we don't try them and thus show a WARN log when we are not using them (appengine).
> fix: logserver not shutting down for appengine

- debug.c
Move a couple of variables declaration inside the `#ifdef ` block to avoid compilation errors
> Fix variables declaration

- scripts/volmount/crypt/crypt
No need to check this anymore as it is shipped along the crypt script
> fix: crypt script checking if x--pv-dcp-tool exists

- .clang-tidy
This PR add a basic but completely functional clang-tidy config file. The file was generated using the `-dump-config` option in order to get the best `CheckOptions`.
It's important to bear in mind that this addition will show a lot of errors, and maybe it's important to solve it before landing to do it in a clean way.
The config file set several configurations related to security issues but, as is suggested in a comment inside, some others checks could be enabled (not enabled now to avoid more warnings and errors):
* performance-*: to check performance improvements.
* cert-*: to check CERT secure coding guidelines (not sure about this one).
* readability-*: this one needs to be tested to check if it fits with our code guidelines.
At the same time, the configuration manages warnings as …
> Add basic clang-tidy config file

- group.c
- group.h
- logserver.c
- platforms.c
- platforms.h
- state.c
- state.h
- utils/timer.c
- utils/timer.h
This PR introduces status for groups. This allows us to monitor and log status changes, so we know when a group is STARTED or READY, for example.
The status of a group is always READY, except when any of the platforms that form the group have not achieved their status goals. In that case, the status of the group corresponds with the platform with the lower status.
It also adds status of the state revision. This status is calculated the same way as the group status, but having into account all platforms in the revision instead.
> introduce group and state status for logging

- ctrl.c
- drivers.c
- grub.c
- logserver.c
- loop.c
- metadata.c
- network.c
- parser/parser_multi1.c
- parser/parser_system1.c
- ph_logger.c
- signature.c
- storage.c
- trestclient.c
- uboot.c
- updater.c
- utils/tsh.c
- wdt.c
Remove some assignments detected as "never read"
Files:
* ctrl.c
* drivers.c
* grub.c
* logserver
* loop.c
* metadata.c
* network.c
* parser/parser_multi1.c
* parser/parser_system1.c
* ph_logger.c
* signature.c
* storage.c
* trestclient.c
* uboot.c
* updater.c
* utils/tsh.c
* wdt.c
> Remove useless assignments from several files

- grub.c
- logserver.c
- metadata.c
- network.c
- pantahub.c
- pantavisor.c
- pvctl_utils.c
- uboot.c
- updater.c
- utils/tsh.c
Replaces all `strcpy` calls with functions who provide boundaries check
> Remove all strcpy and some strcat from Pantavisor

- loop.c
This fixes pantavisor inside docker where loop devnodes are not auto created
> make pantavisor try to mknod the loop device the kernel proposed.

- blkid.c
- grub.c
- logserver.c
- metadata.c
- pantahub.c
- pantavisor.c
- pvctl_utils.c
- uboot.c
- utils/tsh.c
Replace most of strcpy call and other small warnings
> Fix clang-tidy strncpy and other warnings

- atom.mk
- config.c
- pantavisor.c
- scripts/pvcrash
You can now use pantavisor.config sysctl.kernel.core_pattern=|/lib/pv/pvcrash /storage/crash/ to enable crash dumps to /storage/crash/
> add pvcrash handler and stop forcefully registering core_pattern the old way

- buffer.c
- ctrl.c
- log.h
- logserver.c
- mount.c
- parser/parser_multi1.c
- signature.c
- utils/base64.c
Different types of problems are included, problems with memory already freed, uninitialized variables, etc
> Fix clang-tidy warnings

- .clang-tidy
Provides warning-as-errors functionality, without this PR only errors will make the CI fail
> Set all warnings as errors

- init.c
- pantavisor.c
These changes only affect appengine and are needed by the pantavisor script (the that acts as the bootloader for appengine) to leave the infinite loop that emulate the reboot of the device
> handle sigterm for appengine; exit with status 3 in case of poweroff

- atom.mk
- config.h
- log.c
- logserver/logserver.c
- logserver/logserver.h
- logserver/logserver_filetree.c
- logserver/logserver_filetree.h
- logserver/logserver_null.c
- logserver/logserver_null.h
- logserver/logserver_out.c
- logserver/logserver_out.h
- logserver/logserver_singlefile.c
- logserver/logserver_singlefile.h
- logserver/logserver_stdout.c
- logserver/logserver_stdout.h
- logserver/logserver_utils.c
- logserver/logserver_utils.h
- pantavisor.c
- platforms.c
- pvlogger.c
- volumes.c
Creates a new system to allow modular outputs in logserver. The new system uses a base struct to define an output and internally logserver use a list to store the needed outputs (following the configuration).
The current PR includes:
* define a base structure for new outputs (logserver_out)
* rewrite all old outputs using the new system
* creates a small "utils" lib for common functions
> Modular logserver outputs

- logserver/logserver.c
- logserver/logserver_filetree.c
- logserver/logserver_out.h
- logserver/logserver_singlefile.c
Problems: 
- logs aren't written in the right file
- the folder for the new revision are not created, but link to current was updated (and broken)
Now logserver_log include the revision, so the outputs don't need any logic to figure out the current rev.
> Fixes logs on non reboot updates for singlefile and filetree outputs

- logserver/logserver.c
Changes the current behavior, now messages to stdout are sent only if stdout is set. In the current logserver implementation, if the server isn't present (still no active or already closed/killed) the messages are sent to stdout without check if stdout is active
> Adds checks to only send stdout messages if stdout is set

- init.c
Running an app in docker through Cmd or Entrypoint makes the process pid 1. This breaks appengine and this patch addresses that.
IM_STANDALONE is also supported for pid 1 for same reason
> support IM_APPENGINE mode as pid 1

- ctrl.c
An excess of bytes warning is showing when Pantavisor returns an error because the trail characters of the body (\r\n\0) were not taken into account when calculating the Content-Length header:
== Info: We are completely uploaded and fine
<= Recv header, 27 bytes (0x1b)
0000: 48 54 54 50 2f 31 2e 31 20 34 30 30 20 42 61 64 HTTP/1.1 400 Bad
0010: 20 52 65 71 75 65 73 74 20 0d 0a                 Request ..
<= Recv header, 20 bytes (0x14)
0000: 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 3a 20 Content-Length:
0010: 33 34 0d 0a                                     34..
<= Recv header, 47 bytes (0x2f)
0000: 43 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 61 70 Content-Type: ap
0010: 70 6c 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 3b 20 plication/json;
0020: 63 68 61 72 73 65 74 3d 75 74 66 2d 38 0d 0a …
> fix: excess found in error reply

- ctrl.c
In this PR, all send function in pv-ctrl have been grouped in a function so we are consistent and avoid missing incomplete sends without being logged.
> fix: pv-crtl send potentially not logging incomplete sends

- ctrl.c
- parser/parser_system1.c
- platforms.c
- storage.c
* HTTP CONTINUE wrongly logging response not sent
* "nobody" now is accepted as a valid role by parser
* platforms do not check goal timeout after READY
* allocated bigger buffer for logger_name
* revision not starting with /locals is now just an INFO log
* pv_ctrl_flush_req renamed to pv_ctrl_consume_req
> fix: various unnecesary WARN messages in pv logs

- cgroup.c
- cgroup.h
- platforms.c
I appengine, it has been observed that the cgroup that lxc created are sometimes left hanging after we shut it down from the lxc api. This provokes that the next time that container is  started, lxc assigns the same name with a suffix (for example, pvr-sdk-1). To solve this, we can check if the dir is still there after stopping a container and remove it manually as stated in cgroup docs https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html#processes.
For now, this is limited to appengine and to cgroup unified, as those are the conditions under the problem was discovered, but it could be expanded in the future if in happens outside of either appengine or unified.
> fix: cgroup stays untouched after pantavisor shutdown

- plugins/pv_lxc.c
This is a workaround to get some lxc configs work in cgroup v2. Traditionally, we were just switching from lxc.cgroup.devices.allow = a to lxc.cgroup2.devices.allow = a from the lxc plugin. This does not work well with lxc.cgroup.devices.deny = a, as lxc.cgroup2.devices.deny = a does not work well.
With this patch, only in case of cgroup v2, we remove all lxc.cgroup.devices.deny and lxc.cgroup.devices.allow we find, and substitute it with lxc.cgroup.devices.allow= a.
This might change after the LXC 5.0 upgrade, as this issue sugges that it could fix it https://github.com/lxc/lxc/issues/4293
> fix: cgroup deny not allowed in unified

- scripts/volmount/crypt/crypt
In appengine, lib paths might vary, so this patch fixes the LD_LIBRARY_PATH assignation we make in the crypt script.
> fix: crypt LD_LIBRARY_PATH for appengine

- volumes.c
Before this patch, we were trying to umount unexisting volumes in cases of error during container start up. It also improves the umount log traces
> fix: umount of null volumes

- drivers.c
- parser/parser_system1.c
- platforms.c
With this patch, we allow empty aliases en drivers.json:
* pv_drivers_load iterates over the aliases and only evaluates the one that matches, stopping the loop after that
* pv_drivers_load now returns -1 in case of mismatch in the number of loaded and required
* pv_drivers_load can return valid counts from 0 to N
* parser does not fail if bsp/run.json is present in appengine mode
* parser still does not parse the contents of bsp/run.json, but can parse drivers.json
Before this PR, empty aliases would fail if required from a run.json:
```
{
...
"drivers": {
"manual": [
"wifi",
"wireguard"
],
"optional": [],
"required": [
"bluetooth"
]
},
...
}
```
In drivers.json:
```
{
"#spec": "driver-aliases@1",
"all": {
"bluetooth": [],
"usbncm": [],
"usbnet": [],
"wifi": [],
"wireguard": []
}, …
```
> alow empty aliases in bsp/drivers.json

- config.c
- config.h
- pantavisor.c
- wdt.c
- wdt.h
This PR adds a new config key named "wdt.mode" with four possible options:
* disabled: same as old wdt.enabled=0
* shutdown (default): same as old wdt.enabled=1
* startup: the watchdog will be pinged from initialization till the first container is started
* always: the watchdog will be pinged during all Pantavisor operation
This relies on this old kick call that is performed before progressing to any state:
```
static pv_state_t _pv_run_state(pv_state_t state, struct pantavisor *pv)                                              
{
pv_wdt_kick(pv);
return state_table[state](pv);                                                                                    
}
```
And assumes that wdt.timeout will be configured with a value that is bigger than any possible state transition.
> add wdt startup and always operation modes

- config.c
- config.h
- drivers.c
- drivers.h
- init.c
- volumes.c
- Adds interface to load/unload a single driver
- Adds support to load drivers on early stage for standalone and embedded modes
- Cleans initial modules and fw
> Add system.mdev option to load drivers using mdev

- config.c
- config.h
- init.c
Mounts `/sys/kernel/security` needed by AppArmor
> Mounts /sys/kernel/security

- logserver/logserver.c
- logserver/logserver_out.h
- logserver/logserver_utils.c
Previously, logserver was being closed by sending a SIGTERM from the main thread. Then, we waited for 5 seconds max before sending a SIGKILL. The SIGTERM would then be handled from the logserver thread, which would stop accepting pending log entries right away. This would make the logserver to stop printing before the relevant cause of a reboot/rollback was saved in the logs, in some cases, making debugging hard.
This PR proposes a new type of message that can be sent to the logserver socket that would substitute the SIGTERM from the main thread. That way, we know the logserver thread has processed all entries before the command is received. Then, we still wait the 5 seconds max before sending SIGKILL, just in case.
The logserver commands use the version field of the log messages format, …
> fix: logserver exiting before relevant pantavisor.config entries have been sent

- ctrl.c
- pantavisor.c
- signature.c
- signature.h
- storage.c
- storage.h
- updater.c
- updater.h
This is the first delivery in the [improvements of update error reports](https://hackmd.io/33RAIpSSS6SOGj2lDTyAfQ).
Here, we are expand the information given in status-msg in the progress JSON, which can be accessed by `pvcontrol steps show-progress` and `pvcontrol post` commands, following this table:
| Before | After |
| ------ | ----- |
State signatures cannot be verified | Secureboot: State not fully covered by signatures |
State signatures cannot be verified | Secureboot: Signature validation failed |
State cannot be parsed | Parser: State JSON has bad format |
Update aborted | PH Client: Update aborted |
Unable to download and/or install update | PH Client: Max download retries reached |
Space required X B, available Y B | PH Client: Space required X B, available Y B |
> Improve WONTGO status message

- pantavisor.c
- updater.c
- updater.h
Second delivery in the [improvements of update error reports](https://hackmd.io/33RAIpSSS6SOGj2lDTyAfQ).
Here, we are expand the information given in status-msg in the progress JSON, which can be accessed by `pvcontrol steps show-progress` and `pvcontrol post` commands, following this table:
| Before | After |
| ------ | ----- |
Error during update | Secureboot: State not fully covered by signatures |
Error during update | Secureboot: Signature validation failed |
Error during update | Secureboot: Internal error |
Error during update | Checksum: Error during update | Secureboot: Internal error |
Error during update | Container: A container could not be started |
Error during update | Container: Status goal not reached |
Error during update | PH Client: Hub not reachable |
Error during …
> Improve ERROR status message

- atom.mk
- config.c
- config.h
- logserver/logserver.c
- logserver/logserver_out.h
- logserver/logserver_singlefile.c
- logserver/logserver_timestamp.c
- logserver/logserver_timestamp.h
- logserver/logserver_utils.c
- Adds `log.timestamp.format`
- Adds some shorthand for well known timestamp format (WIP)
- Change how the JSON log is built, now use the PV JSON lib
> Adds timestamp in singlefile json log

- storage.c
- storage.h
- updater.c
- updater.h
This problem was brought  to surface by  the [ERROR status message improvements](https://github.com/pantavisor/pantavisor/pull/348) and only affect remote mode.
All the ERROR status-msg before that PR were "Error during update". As now that has changed, it turned out that all the errors that were set before stablishing contact with PH were being overwritten by "PH Client: Stale revision".
With this PR, we load the status that was last set during the INPROGRESS and TESTING before a rollback and send it to PH so the status-msg corresponds with the actual cause of error.
It also attaches the revision of an update to the update struct itself instead of using the status one, which would cause Pantavisor to not update the progress JSON of an update until the signature validation and state …
> fix: PH client not properly updating status error after rollback

- ctrl.c
The WARN that is shown when trying to put an object from ctrl would look like this:
```
[pantavisor] 2691 WARN – [ctrl]: 627413120286311 B needed but only 7306916064555987759 B available. Cannot create file
```
With this PR, the format of the printf is fixed to show the right values. Also, strtol to get the HTTP content-length value has been changed to strtoul to support bigger values without overflow.
> fix: wrong size of objects in logs when trying to put an object

- pantavisor.c
- storage.c
- updater.c
- updater.h
- utils/fs.c
This PR completely refactors the update status progress reporting code with these goals in mind:
* serialize the progress JSON in one place instead of using multiple different defines
* make it easier to add a configurable limit of size of the JSON
* make it easier to add new fields to the JSON, such as the logs
* use the JSON serialization utils functions
> refactor: update status report

- atom.mk
- config.c
- config.h
- ctrl.c
- logserver/logserver.c
- logserver/logserver_out.h
- logserver/logserver_singlefile.c
- logserver/logserver_update.c
- logserver/logserver_update.h
- logserver/logserver_utils.c
- paths.h
- updater.c
- updater.h
- utils/fs.c
- utils/fs.h
- utils/json.c
- utils/socket.c
- utils/socket.h
This PR introduces a new logserver sink to store update related logs. Unlike other sinks, this one can compile in a single file logs that come from two different revisions (the updated and the updater) and is enabled by default during updates.
The ultimate objective is to show these logs stored by the update sink in the update progress JSON, which is currently used both for remote and local experience update feedback. These logs provide additional information in case of WONTGO or ERROR. For example:
```
{
"status":"ERROR",
"status-msg":"A container could not be started",
"progress":100,
"logs":"{\"tsec\":10214,\"tnano\":0,\"platform\":\"pantavisor\",\"lvl\":\"ERROR\",\"src\":\"platforms\",\"msg\":\"error starting platform: 'pvr-sdk'\"}\n{\"tsec\":10214,\"tnano\":0,\"platform\":\"pantavisor …
```
> feature: logserver update sink

- disk/disk.c
- disk/disk.h
- pantavisor.c
- parser/parser_system1.c
- state.c
- volumes.c
This PR address several problems/improvements mentioned in the original disk PR:
* Replace API to use disk (struct dl_list *disks) instead of pv_state *s
* Remove some confusing logs.
* Remove unused #define
* Change API to mount/umount disk
* Rename disk parse functions
* Adds checks to detect unknown formats in the parser
> Fixes problems from original disk PR

- debug.c
- debug.h
- init.c
- platforms.c
- plugins/pv_lxc.c
- utils/tsh.c
- utils/tsh.h
* introduce a background pid pool so we can reap them without stopping pantavisor
* introduce tsh facilities to push and pop tracked pids
* remember forked lxc processes that exit after daemonizing as background ids
* remember tsh_run pids started in background in pid pool
* also fix potential issues in run processes by resetting sigmask in child
>  Rework init reaping code so it reaps only direct childs

- debug.c
- debug.h
- init.c
- platforms.c
- plugins/pv_lxc.c
- utils/tsh.c
- utils/tsh.h
* introduce a background pid pool so we can reap them without stopping pantavisor
* introduce tsh facilities to push and pop tracked pids
* remember forked lxc processes that exit after daemonizing as background ids
* remember tsh_run pids started in background in pid pool
* also fix potential issues in run processes by resetting sigmask in child
> Rework init reaping code so it reaps only direct childs.

- parser/parser_system1.c
- signature.c
- storage.c
Fixing various memleaks related to unfreed artifacts from state JSON parser:
* storage disk name not being freed after volume-disk linking
* json list values not being freed after validation
* signature pvs not being freed after signature parsing
* device.json duplication during parsing
> fix: parser artifacts memleaks

- parser/parser_multi1.c
- parser/parser_system1.c
- state.c
- state.h
- storage.c
- updater.c
JSON state memory was being allocated 3 times per update:
* first one, to get the contents from the storage on disk into memory for signature validation and parsing.
* during parsing, we were storing the json in the state struct for later use, which can be avoided.
* during revision installation, we were duplicating once again to parse the JSON and search for other JSONs to be installed in /storage/trails. This is also not necessary as we already store a list of all JSONs in the state struct.
While this was not a memory leak, it was a great waste of resources and was messing the heap when Pantavisor was trying to allocate such big buffers. As a refrence, a regular state JSON with 3 containers can take 22KB aprox.
On this PR, we avoid storing the state JSON in the state struct, which …
> fix: JSON state being duplicated 3 times per update

- ctrl.c
- ctrl.h
- log.h
- pantavisor.c
- state.c
- state.h
- storage.c
- storage.h
- updater.c
Adds a new ctrl command to force remote in a locals/ revision. This can be used to claim a device in any locals/ revision or claim it, go local and then allow to get back to remote without having to rollback.
To use the command with curl:
```
curl -X POST --header 'Content-Type: application/json' --data '{"op":"GO_REMOTE","payload":""}' --unix-socket /var/run/pv-ctrl.pantavisor http://localhost/commands
```
A pvcontrol command will be added too.
The command will only work if:
* device is not in remote mode already
* control.remote is enabled by config
Additionally, we now store if a revision update was DONE in memory (we were already doing it on disk). This is later used to disable claiming revisions that are not DONE.
> feature: ctrl command go remote

- storage.c
This PR fixes a regression introduced with https://github.com/pantavisor/pantavisor/pull/382/. 
When we install a new update, we create links for the objects and save the json files from the main revision json. If the json file already exists, we should just skip the file and continue, but we were actually returning an error. This problem will manifest when trying to run an already run revision.
> fix: updater expand json failing when file exists

- scripts/volmount/crypt/crypt
- scripts/volmount/verity/dm
It has been observed in App Engine that, if Pantavisor cannot properly shutdown, it would leave remnants for the next execution. This would make Pantavisor fail unless the host machine were rebooted.
With this PR, we want to preemptively close those crypt and dmverity vols before trying to initialize them.
> fix: dmverity and crypt disks not being preemptively closed

- config.c
- config.h
- init.c
- log.c
- logserver/logserver.c
A new sink meant for early init and crash debugging. It works in a similar way as stdout with two differences:
* when enabled, stdout_direct messages are directly printed from the calling thread. This means, it will not pass through logserver.
* If stdout is enabled and logserver is off (before its initialization and after its shutdown), it behaves the same way as stdout_direct.
* All FATAL level logs will be printed using this method no matter the sink is enabled.
To enable it in cmdline:
`pv_log.server.outputs=stdout_direct`
In config:
`log.server.outputs=stdout_direct`
> new stdout_direct logserver sink

- logserver/logserver_filetree.c
- logserver/logserver_utils.c
- logserver/logserver_utils.h
Adds timestamp format to the container's log output, this is:
```
<container>/lxc/lxc.log
<container>/lxc/console.log
<container>/var/log/messages
<container>/var/log/syslog
```
To avoid break any log format, the timestamp was added at the begging of the lines logs.
**Note:** some logs arrive in lines batches, those logs only have a timestamp at the begging of the first line
> Fixes logserver timestamp format in filetree output

- atom.mk
- bootloader.c
- config.c
- config.h
- grub.c
- parser/parser_system1.c
- paths.h
- rpiab.c
- rpiab.test.c
- state.h
- storage.c
- uboot.c
- updater.c
- utils/pvzlib.c
- utils/pvzlib.h
rpiab booloader support for Raspbery Pi Firmware A/B tryboot
* ship pantavisor and kernel as part of full raspberry pi boot partition
* install dtbs to boot partition from kernel
* use mcopy to copy autoboot.txt to and from partition 1
* patch cmdline.txt in boot-a/b partition to have pv_rev
* add pvzlib.c/h helper to support shipping gzipped boot partitions
* add support for shipping 'rpiab' partition in run.json
* parse /proc-device-tree and autoconf.txt in early boot to find tryboot
info and partition and boot disk (through boot-mode)
* set tryboot flag through IOCTL_MBOX_PROPERTY ioctl (mbox_property)
Example run.json:
{
"addons": [],
"firmware": "firmware.squashfs",
"initrd_config": "trail.config",
"modules": "modules.squashfs",
"rpiab": "pantavisor-rpi.img.gz"
}
See: …
> rpiab booloader support for Raspbery Pi Firmware A/B tryboot

- bootloader.c
- bootloader.h
- parser/parser_system1.c
- rpiab.c
- state.c
- storage.c
- updater.c
This PR contains the corrections for https://github.com/pantavisor/pantavisor/pull/402:
* bootloader: use a single set of install, commit and fail functions in bootloader.h
* bootloader: fix install failing in case the new bootloader semantic is not being used
* parser: make parsing fail in case bootimg is not specified and we are expecting it by config
* rpiab: remove pv_update and pv_state from interfaces. Only used to check bootimg not set, which was moved to parser (see previous bullet). Changed in favor of char *rev to make it more similar to the rest of the bootloader types
* state: free bootimg in pv_state_free
* updater: call bootloader installed and commit functions only once. In the case of pv_bootloader_commit_update, it has been changed to the old place. IMO it makes no sense …
> fix: rpiab bootloader support breaking other bootloaders

- blkid.c
- utils/fs.c
- utils/fs.h
Adds to blkid lib the ubifs detection using /sys filesystem:
1. Checks the fs with pv_config_get_storage_fstype()
2. Gets the device and volume names from pv_config_get_storage_path(), normally in the format device:volume (e.g. ubi0:pvroot)
3. Checks the device in /sys/devices/virtual/ubi
4. Checks all volumes names, if the volume it's found, then the path in format /dev/<device> will be written in the blkid_info struct
> Fixes detection of ubifs volumes

- drivers.c
- platforms.c
- platforms.h
Fixes the unload/load problem, setting the `loaded` field in the `pv_platform_driver` struct
> Fix driver loading/unloading

- config.c
Although cmdline config plays well with empty values, sysctl was not writing those values into /proc/sys because we were using strlen(value). With this change, we include the trailing character to fix the problem.
> fix: sysctl write missing trailing character

- pantavisor.c
- rpiab.c
- updater.c
* Remove unnecessary fclose(), on rpiab.c:239
* Remove an "always true" condition , on updater.c:466 
Both are warning (and errors due to -werror) with the new compiler
> Fixes problems found to update the toolchain

- CMakeLists.txt
- atom.mk
- init.c
- plugins/CMakeLists.txt
[Switch build system to CMake for alchemy and yocto](https://github.com/pantavisor/pantavisor/pull/409/commits/15f59528378b5eeddfdbb290290655f30cdcf224) 
install trust certs from PANTAVISOR_PVS_DIR
CMake Flags:
PANTAVISOR_DEBUG=ON - passes -DPANTAVISOR_DEBUG to build
PANTAVISOR_DM_VERITY=ON - enable dm verity feature
PANTAVISOR_DM_CRYPT=ON - enable dm crypt disk feature
PANTAVISOR_TESTS=ON - build tests
atom.mk:
- move all build targets to BUILD_CMAKE or BUILD_CUSTOM (for dummy support)
- use CONFIG_ALCHEMY_BUILD_INIT_DM to enable PANTAVISOR_DM_VERITY feature flag
- use CONFIG_ALCHEMY_BUILD_INIT_CRYPT to enable PANTAVISOR_DM_CRYPT feature flag
- introduce pvtests module to build pantavisor including tests
Create skeleton dirs at runtime
- mkdir /tmp and early mount dirs
- install scripts …
> Initial CMake support for yocto

- config.c
- config_parser.c
- config_parser.h
This PR adds the sysctl config keys to the [Linux env configurable list](https://github.com/pantavisor/pantavisor/pull/429):
* The old format (e.g: "sysctl.kernel.core_pattern") is still supported.
* A new env friendly format (e.g: "PV_SYSCTL_KERNEL_CORE_PATTERN") is now supported. This is parsed by checking for existing dirs when reaching a '_' character. If true, then it is switched with a '/'.
> allow sysctl config from env

- logserver/logserver_utils.c
This PR detects some lines where the final CRLF comes in a separate messages and do not add the timestamp for those lines
> Fixes double timestamp by detection splitted messages

- logserver/logserver_utils.c
Now Pantavisor log looks like this:
```
[1970-01-01T00:23:20] [pantavisor] 10 DEBUG      -- [logserver]: starting logserver loop
[1970-01-01T00:23:20] [pantavisor] 10 DEBUG      -- [logserver]: started log service with pid 79
[1970-01-01T00:23:20] [pantavisor] 10 DEBUG      -- [log]: initialized pantavisor logs...
[1970-01-01T00:23:20] [pantavisor] 10 INFO       -- [log]: ______           _              _
[1970-01-01T00:23:20] [pantavisor] 10 INFO       -- [log]: | ___ \         | |            (_)
[1970-01-01T00:23:20] [pantavisor] 10 INFO       -- [log]: | |_/ /_ _ _ __ | |_ __ ___   ___ ___  ___  _ __
[1970-01-01T00:23:20] [pantavisor] 10 INFO       -- [log]: |  __/ _` | '_ \| __/ _` \ \ / / / __|/ _ \| '__|
[1970-01-01T00:23:20] [pantavisor] 10 INFO       -- [log]: | | | (_| | | | | || …
```
> Moves timestamp at the beginning of the lines

- config.c
- config.h
- init.c
- pantavisor.c
- parser/parser.c
- parser/parser.h
- parser/parser_multi1.c
- parser/parser_multi1.h
- parser/parser_system1.c
- parser/parser_system1.h
- signature.c
- state.c
- state.h
This PR is a continuation of the [OEM signature trustore](https://github.com/pantavisor/pantavisor/pull/436).
In order to keep the configuration as small as possible, `PV_SECUREBOOT_OEM_CN_NAME` is now named `PV_OEM_NAME`. The same functionality for secureboot from the previous PR is kept.
This new `PV_OEM_NAME` can also be used to load additional configuration from containers, with the following behavior, when defined:
* If PV_POLICY is set, the file is loaded from the trail file <PV_OEM_NAME>/<PV_POLICY>.config
* If PV is not set, the file is is loaded from <PV_OEM_NAME>/default.config
* If the configured file is not found, we continue normally with a log WARN.
Additionally, trail config (now, bsp config) is now done after signature validation and before oem config.
All config levels …
> OEM configuration level

- config.c
- config.h
- ctrl.c
As pvcontrol config ls will keep returning the old config format (e.g. creds.host=api.pantahub.com) for backwards compatibility reasons, this PR offers a new request to return the new format, adding at which level the item was set.
For example:
```
[
{
"key": "PH_CREDS_HOST",
"value": "api.pantahub.com",
"modified": "ph conf file"
},
...
{
"key": "PV_DEBUG_SHELL_AUTOLOGIN",
"value": "0",
"modified": "default"
},
...
{
"key": "PV_UPDATER_GOALS_TIMEOUT",
"value": "10",
"modified": "pv conf file"
},
...
]
```
> new request in ctrl to return the new config format table

- config.c
While initrd_config key is still supported in src.json. Pantavisor will only print a WARN in logs when defined and continue without loading it.
> stop supporting deprecated BSP config

- logserver/logserver_singlefile.c
- logserver/logserver_utils.c
- logserver/logserver_utils.h
* Adds a new parser for /dev/kmsg, extracting the timestamp and formatting it in the same way that the `dmesg` command does it
* Splits logs with multiple lines (like `/dev/kmsg`)
> Format /dev/kmsg logs in the same way as dmesg

- logserver/logserver.c
- logserver/logserver_utils.c
- logserver/logserver_utils.h
This PR allow to logserver set `ignore_loglevel` and `printk_devkmsg=on` when is needed, this is when some of the stdout* outputs is active (both options in this case) or when pv_capture_dmesg is true (only `printk_devkmsg=on`)
> Sets automatically ignore_loglevel and printk_devkmsg=on when is needed

- updater.c
- updater.h
Before this PR, we were making 5 GET requests when idle for every cycle:
* trails/ to check if the device was synced
* trails/id/steps/requests?progress.status=NEW to list NEW pending revisions
* trails/id/steps/requests?progress.status=QUEUED
* trails/id/steps/requests?progress.status=DOWNLOADING
* trails/id/steps/requests?progress.status=INPROGRESS
With this PR, we reduce the number of request per cycle:
*  trails/id/steps/requests?progress.status=%7B%22$in%22:%5B%22NEW%22,%22DOWNLOADING%22,%22INPROGRESS%22,%22QUEUED%22%5D%7D is now done to request all pending revisions with just one request
*  trails/id/steps/requests?progress.status=NEW is still used to send all NEW revisions into QUEUED while an update is being installed
* trails/ is still used but just once for each reboot. After …
> refactor: merge all /trails requests when idle

- metadata.c
- pantahub.c
Before this commit, we were parsing the user metadata from the response of GET /device/id. This can be optimized with the new /device/id/user-meta endpoint, which returns the user metadata only.
> refactor: reduce the scope of usermeta requests to hub

- ctrl.c
This PR fixes a freeze that occurred when putting an object using pvcontrol whose .tmp file already existed in /storage, due to a porwercycle or any other interruption that could make the transfer stop unexpectedly.
The freeze was happening in the open function from standard library because of conflicting flags that would result in undefined behavior:
```
obj_fd = open(file_path, O_CREAT | O_EXCL | O_WRONLY | O_TRUNC, 0644);
```
In this case, we are using O_EXCL, to return an EEXIST error in case the file to create already existed, plus O_TRUNC, to erase the file and create it with size 0.
As these two are mutually exclusive, we are removing the O_EXCL flag and the subsequent code to handle EEXIST. In case a .tmp file exists, we will just overwrite it. In case the object itself exist, we …
> fix: open object .tmp file using conflicting O_EXCL and O_TRUNC flags

- config.c
- config.h
- init.c
- mount.c
- pantavisor.c
- paths.h
- state.c
- state.h
This PR enables the storage of pantahub.config and unclaimed.config files in a volume, which allows to set that volume into a crypt disk.
The feature is enabled the same way one would assign metadata to a volume in device.json so, it is enabled at the revision checkout level:
```
{
"disks": [...],  
"groups": [...],  
"volumes": {
"pv--phconfig": {
"disk": "secrets",
"persistence": "permanent"
}
}   
}
```
A new optional config key has been added to force the feature enablement. When true, a revision without the "pv--phconfig" volume will not be bootable:
```
PV_STORAGE_PHCONFIG_VOL=1
```
The changes that have been necessary to get this can be summarized like this:
* Pantavisor now works with pantahub.config and unclaimed.config in a new location in /pv/phconfig/
* If a volume with the …
> feature: pantahub.config can be stored in a volume

- updater.c
Current revision whose update status was not updated in cloud should never be set as stale. In that case, it is preferable to load the status from storage and try to push that to cloud.
> fix: current running revision being set as stale

- pantavisor.c
- ph_logger.c
- ph_logger.h
This PR fixes ph_logger not being compatible with tmpfs (because of xattr).
The code in charge of managing the offset of the devices, which relied completely on writing/reading xattr from files,  has been moved to two functions:
*  _save_log_file_pos: it saves the offset on memory and as an xattr in files if possible by config.
* _load_log_file_pos: it loads the offset from memory, of not available from xattr, it takes 0 as the initial point.
The offsets are stored in memory as a list of paths and position offsets in ph_logger struct.
> fix: ph logger not working with tmpfs logs

- blkid.c
- rpiab.c
- signature.c
- uboot.c
1. Fixes possible truncation in snprintf now the new size is PATH_MAX + NAME_MAX + 2 (for the glob expression) + 1 (the 0) in blkid.c:258
2. Fixes the way how the new string size is acquired in rpiab.c:363, 367, 377, 381, 392
3. Addscast to match the right type in signature.c:634
4. Removes spurious \0 in snprintf call
> Fix warnings and errors after the toolchain migration

- pantahub.c
- pantahub.h
- pantavisor.c
- state.c
- state.h
- storage.c
- updater.c
This PR fixes a regression introduced in [453](https://github.com/pantavisor/pantavisor/pull/453).
After that PR, pantahub.config file is loaded in a later stage during bootup initialization, specifically after status JSON is loaded, once we have the device.json volume information. At the time, this meant moving all processes that were using PH_*config keys after that new loading point. In that development, some of those were missing, and are causing now the following symptoms:
* Remote claimed devices not recovering its stored credentials after reboots, including update reboots. In this case, the device would create new claiming credentials, resetting the claiming process.
* Remote claimed devices not being able to boot up both local and remote revisions. This would cause a freeze …
> fix: not loading Pantacor Hub creds between reboots

- scripts/volmount/verity/dm
- state.c
- utils/str.c
- utils/str.h
This PR introduces a new method to obtain the "no validation list" (NVL) without using the `dm` script. The process is based on the current `pv_state` present in the `pantavisor` structure, where 2 lists are used to build the NVL `pv_object` list and `pv_json` list.
First, the known objects are added using the expressions found in the `dm` script. Then, objects with type = `dm-verity` in the `pv_json` list are located in the `pv_object` list and added to the NVL.
> Improve the creation of "no validate" list

- remount/remount.c
free_remount_entry was being called everytime after parsing the entries. This would cause a crash further on when those entries were being iterated over.
> fix: new remount LXC hook crashing

- remount/remount.c
This was causing compilation problems for nv-tegra-4_9 platform.
> fix: define MS_NOSYMFOLLOW in remount not supported until Linux 5.10

- parser/parser_system1.c
- platforms.c
- platforms.h
- plugins/pv_lxc.c
The field `export` (bool) is added to pv_platform to avoid run the export hook when the platform has not a export definition.
* the field is initialized as false (platforms.c)
* the field is set to true during the state json parsing. (parser_system1.c)
* export hook is not added if the export is false. (pv_lxc.c)
> avoid running export.sh hook when defined in run.json

- init.c
- logserver/logserver.c
- pantavisor.c
- ph_logger.c
- platforms.c
- pvlogger.c
- rpiab.c
- signature.c
- state.c
- storage.c
- uboot.c
- updater.c
This PR fix all wrong string formatter applied to logs, snprintf, printf and any other function where a formatter was used.
For special types like `time_t` or `off_t` formatter was replaced with `%jd` or `%ju` for `intmax_t` or `uintmax_t` as far as I know, this is the best option in a modern C code base
> Fix malformed strings

- platforms.c
- updater.c
Fix some possible integer overflows in memory assigns, and maybe the most relevant in the libthttp.
**IMPORTANT:** to merge this PR, please fist check and merge this: https://gitlab.com/pantacor/libthttp/-/merge_requests/49 which implements the solution in the libthttp side
> Fix interger overflows

- bootloader.c
- bootloader.h
- buffer.c
- buffer.h
- grub.c
- logserver/logserver.c
- pantavisor.c
- parser/parser_system1.c
- platforms.c
- plugins/pv_lxc.c
- rpiab.c
- state.c
- uboot.c
- ubootab.c
This PR fixes the memory warnings detected by Valgrind during Pantavisor bootup and shut down (no containers):
* bootloader: global strings not being freed before power off.
* buffer: global struct and buf not being freed before power off.
* logserver: msg not initialized to 0 in logserver_send_subs_msg.
* logserver: ignoring open socket error in logserver_send_subs_msg.
* parser: str being freed when NULL.
* platforms: config being freed but not the list of configs itself.
* pv_lxc: closing fd in case of open error in pv_setup_lxc_container.
* state: novalidate list trailing byte not being initialized.
> fix: several memory problems unearthed by valgrind mem check

- storage.c
- utils/fs.c
- utils/fs.h
Create an array to store the inode of each file with an already calculated checksum to avoid the recalculation
> fix: avoid checksum calculation over the same file

- config.c
Before this PR, configuration level overwrite would be defined by its loading order (defaults -> pv.conf -> pv_ cmdline -> env -> policy -> OEM -> ph.conf -> ph_ cmdline -> user-meta -> command). 
This would present two problems:
* Env would not overwrite policy and OEM configs.
* Legacy pv_ cmdline would not overwrite policy and OEM configs.
This fix, preserves the loading order of the different levels, as that will allow to load PV_POLICY and PV_OEM_NAME in the right places, while it will introduce a new hierarchy of levels. The new hierarchy prevents lower levels to overwrite upper levels, following this order:
defaults < pv.conf/ph.conf < policy < OEM < cmdline < env < user-meta < command
Besides the parsing order, the change also keeps the allowed levels for each key untouched.
> fix: env conf not overwriting ph.conf and OEM conf

- CMakeLists.txt
The subdirectory inclusion cause conflicts with other targets since that directory implies the dependency from lxc, for that reason the inclusion was moved inside PANTAVISOR_RUNTIME
> Allow to build secondary targets without the lxc dependency

- pvtx/pvtx.c
- pvtx/pvtx_txn.c
```
Usage: ./pvtx COMMAND [SUB-COMMAND] args...
Commands:
begin <base> [object] Creates a new transaction.
The first argument <base> could be a real revision,
"" (empty string, use current rev) or "empty" (empty revision).
Transactions created without an object_path are called remote
transactions and its objects sent directly to the pv-ctrl socket.
add <file> or -       Adds a json or tarball to the current transaction.
Alternatively '-' could be used to read from stdin.
abort                 Commit transaction, valid only for remote transactions.
commit                Show the current state json.
show                  Show the current state json.
deploy <directory>    Deploy the current transaction in the given directory.
help <file>           Show this help and ends.
queue <sub-command> …
```
> Add help and minor fixes to how some args are processed

- CMakeLists.txt
- pvtx/pvtx.c
- pvtx/pvtx_buffer.c
- pvtx/pvtx_buffer.h
- pvtx/pvtx_ctrl.c
- pvtx/pvtx_tar.c
- pvtx/pvtx_tar.h
- pvtx/pvtx_txn.c
Add dynamic buffer to read and write operations
Dynamic buffers are implemented to send and receive objects and json from pv-ctrl (pvtx_ctrl) and to read and write objects to folders (pvtx_txn), those buffers can be set to use different sizes, although they have minimum and maximum values. The following table shows a small summary for each one:
| variable name        |        operation       |    minimum   |     maximum     |
|----------------------|------------------------|--------------|-----------------|
| PVTX_CTRL_BUF_SIZE   | for pv-ctrl operations | 16384B (16K) | 10485760 (10M)  |
| PVTX_OBJECT_BUF_SIZE | for write/read objects | 512B         | 10485760B (10M) |
> Add dynamic buffer to read and write operations

- ph_logger.c
Now range service instead shows one line per log sent, just show one line per revision with the number of logs sent
example:
```
[pantavisor] 54 DEBUG    -- [ph_logger]: Range service push 89 logs for rev 3
other non-related logs here... 
[pantavisor] 36 DEBUG    -- [ph_logger]: Range service push 0 logs for rev 4
```
> fix: make ph-logger range service less noisy

- metadata.c
- utils/json.c
- utils/json.h
When storing bad formatted JSON in device metadata, Pantavisor was unable to upload it as the HTTP request was bad formatted too. Escaping bad formatted JSON in these cases will solve this.
It also affected pvcontrol, which is now returning a JSON that contains escaped bad formatted JSONs too.
> fix: escape bad formatted JSON devmeta

- pvtx/pvtx.c
- pvtx/pvtx_ctrl.c
- pvtx/pvtx_error.c
- pvtx/pvtx_error.h
- pvtx/pvtx_state.c
- pvtx/pvtx_tar.c
- pvtx/pvtx_txn.c
- utils/fs.c
- utils/fs.h
Adds secure operation over files, doing all the work behind the scenes using temporal files and then moving it using rename(3)
The Idea it's to avoid the data lost while files are being created.
The changes introduced are:
* Improve the current function in utils/fs to create temporal files.
* Adds new function to create temporal directories. 
* Add "write in temporal then move" logic to all critical operations
**Update**:
* Adds PV_FS_NO_SYNC macro to avoid call sync() in the utils/fs functions, so if this macro is defined the developer is responsible to call sync() when is needed
> Atomic file ops in PVTX

- CMakeLists.txt
A deprecation warning suggest that the compatibility with CMake < 3.10 will be removed, so this commit bump the minimum version to avoid that future problem.
The warning appears as soon as Pantavisor build is set:
```
$ cmake -DPANTAVISOR_RUNTIME=OFF -DPANTAVISOR_PVTX=OFF -DPANTAVISOR_PVTX_STATIC=ON ..
CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
```
> Bump minumum cmake version

- ctrl.c
- pantavisor.c
This PR fixes a regression introduced with the event loop, as now we are able to process several ctrl requests in between two PV_STATE_WAIT iterations. The last request received before a PV_STATE_WAIT would overwrite any commands (pvcontrol cmd run-gc, reboot, run, etc.) sent after the previous PV_STATE_WAIT.
To fix this, no more than one command in between two PV_STATE_WAIT is now allowed. Furthermore, a 409 HTTP error code will be returned in case the user tries this.
> fix: ctrl requests overwriting not yet processed commands

- ctrl.c
- ctrl.h
- pantavisor.c
- updater.c
- updater.h
This feature enable, using pvcontrol, a way for applying the rev rebooting after the command.
On `pvcontrol` we will run as the following: `pvcontrol cmd run-commit <rev>` . MR for pvr-sdk is [here](https://gitlab.com/pantacor/pv-platforms/pvr-sdk/-/merge_requests/104) 
I add a new entry on pv_update structed, so when we use run-commit we set mark that, after applying the rev, we will reboot the system.
The flow is the same as a normal `pv_update` 
I'm a little confused about the `CMD_LOCAL_APPLY` it looks same with  `CMD_LOCAL_RUN` but there are some differences. What is that about?
I don't know if I'm missing any edge case during test.
> feat: support to update and commit
