atom.mk, init.c, mount.c, pantahub.c, pantavisor.c, trestclient.c, utils/fops.c, utils/tsh.c, utils/tsh.h
In this change:
* move tsh to utils
* add new tsh_run_output function that returns out and err in a buffer
=> tsh_run_output that returns out and err in a buffer

utils/tsh.c
* make it wait until command has finished or timed out
* kill command sub process with sigterm if time out
* in case of time out, set errno to ETIME
* return command status code
=> wait in tsh_run_output until command has finished

state.c
=> fix crash if searching validate_list no dm handler is available

state.c
=> make failing volmount handlers like for novalidatelist subcommand non fatal

state.c
fix regression introduced with https://github.com/pantavisor/pantavisor/pull/44
* state: app status now listed in state conditions so state fails if any app cannot be started
* state: new jsons taken into account to determine whether to reboot or not after a transition
* state: new objects taken into account to determine whether to reboot or not after a transition
=> consider new json and objects when transitioning for an update

plugins/pv_lxc.c
(regression from previous landing
=> fix non-mgmt platforms failing to mount control sockets

ctrl.c, utils/str.h
Make our header searcher case insensitive to comply with https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
=> fix content length case insensitive

storage.c
Add total and free disk space to devmeta
=> add storage info to devmeta

condition.c, ctrl.c, parser/parser_system1.c, platforms.c, platforms.h, plugins/pv_lxc.c
Refactor roles so it easier to add new ones.
* conditions: use pv_json_ser library to generate json
* ctrl: use new role function to check mgmt
* parser_system1: use new role functions to set and unset mgmt
* platforms: store roles with masks
* platforms: offer new functions to modify and check mask
* platforms: use pv_json_ser library to generate json
* platforms: show roles in platform json for pvcontrol ls
=> refactor roles and add them to pvcontrol ls

bootloader.c, buffer.c, config_parser.c, ctrl.c, drivers.c, grub.c, init.c, log.c, metadata.c, mount.c, network.c, objects.c, pantahub.c, pantavisor.c, parser/parser_multi1.c, parser/parser_system1.c, ph_logger/ph_logger.c, plugins/pv_lxc.c, pvlogger.c, signature.c, state.c, storage.c, uboot.c, updater.c, utils/base64.c, utils/json.c, utils/system.c
Refactor all `calloc` calls used to assign memory to `char` pointers.
=> Refactor calloc

ctrl.c, init.c
... to determine ctrl socket caller container
=> create and use named pantavisor cgroup (name=pantavisor)

metadata.c
The output of `pvcontrol devmeta ls | jq` is something like:
```json
{
"storage": {
"total": 15610982400,
"free": 15318548480,
"reserved": 780549120,
"real_free": 14537999360
},
"pantavisor.version": "015-rc4-32-gfe4e999-220622-136fbe4",
"pantavisor.uname": {
"kernel.name": "Linux",
"kernel.release": "4.19.127-v8+",
"kernel.version": "#1 SMP PREEMPT Tue Jun 14 19:59:42 UTC 2022",
"node.name": "(none)",
"machine": "aarch64"
},
"pantavisor.revision": "locals/pbox-1655906948",
"pantavisor.mode": "local",
"pantavisor.dtmodel": "Raspberry Pi 3 Model B Plus Rev 1.3",
"pantavisor.arch": "aarch64/64/EL",
"pantahub.state": "update",
"pantahub.online": "0",
"pantahub.claimed": "1",
"pantahub.address": "163.172.132.38:443",
"interfaces": {
"lo.ipv4": [
"127.0.0.1"
],
"enxb827eb52df46.ipv4": [ …
```
=> Add uname data on different keys

metadata.c, metadata.h
See the description of the fields here https://man7.org/linux/man-pages/man2/sysinfo.2.html
=> Add sysinfo fields to devmeta

ctrl.c
=> fix pv_ctrl_process_put_file unnecessary slow on put due to O_SYNC

ctrl.c, logserver.c
There were a number of misuses of the bind function in both logserver and ctrl:
* the third argument of bind should be the size of the addr struct, not the addr.sun_path size ([source man page](https://www.man7.org/linux/man-pages/man2/bind.2.html))
* addr.sun_path not properly initialized to 0 to avoid buffer overflows  ([source man page](https://www.man7.org/linux/man-pages/man2/bind.2.html))
=> fix: bind not being used as in the man example

log.c
Fix code style in the initial log message
=> Fix code style

logserver.c, logserver.h, platforms.c
* Add loglevel to `logserver_subscribe_fd`
* Set INFO as default loglovel for containers fds
=> Implement loglevel on subscribed fds

ctrl.c
This PR fixes two bad behaviors related to pvctrl:
* pantavisor unexpectedly ending after a write call raised a SIGPIPE
* pantavisor main thread blocked if a container sends an uncomplete HTTP request
* ctrl: write calls substituted with send ones with the MSG_NOSIGNAL flag to ignore SIGPIPE
* ctrl: read calls susbtituted by select+recv with flag MSG_DONTWAIT to avoid blocking
* ctrl: better error log tracing
=> fix: avoid pvctrl exit and block on incomplete HTTP requests

parser/parser_system1.c
…date all device level bits into one json.
For now we added support for groups.json and disks.json here using groups and disks
=> introduce a top level device.json element

log.c, mount.c, pantavisor.c, storage.c
=> improve umount so that errors get logged and do fs syncs before reboot

ctrl.c
* we check hashsum of target object
* if exist we dont replace it with a new upload
* this reduces unecessary inode shuffling and disk duplication
=> stop replacing good objects in ctrl PUT /objects

group.c, group.h, pantavisor.c, parser/parser_system1.c, state.c, state.h
Implements groups timeout:
- rollback if a group cannot achieve his status-goal before the timeout
- unblock platform boot if previous group cannot achieve his status-goal
=> Groups timeout

config.c, config.h, paths.c, paths.h, signature.c
* move trust certs and pub keys into folder /etc/pantavisor/pvs/trust/
=> make truststore configurable through securetboot.truststore

state.c
When we do a non-reboot updates, we transfer objects, jsons, platforms and volumes from the new state struct (that will be later discarded) to the current one (the one that was booted, which will be preserved after non-reboot transition). We also have to relink the new volumes from the new state to the disks in the old state, otherwise, those will be pointing disks from the new state that will be freed.
=> fix: disk transfer in non-reboot updates not taking place

pvlogger.c
Fix pvlogger (messages and syslog)  missing LF
=> Fix lost LF on message and syslog

debug.c
…h pv:user-meta as config value
=> allow to explicitely select user-meta location as authorized_keys 

atom.mk, logger.c, logger.h
inline libpvlogger code
* copy logger.c and logger.h from libpvlogger
- d2043bd105c51ab5d1fcd4ab0cd6464f82561556
* update atom.mk to not link against libpvlogger
* update atom.mk to also build logger.c
=>  inline libpvlogger code 

ctrl.c, plugins/pv_lxc.c, utils/system.c, utils/system.h
based on https://github.com/systemd/systemd/blob/main/docs/CGROUP_DELEGATION.md
=> use correct names for cgroup version consts

scripts/hooks_lxc-mount.d/remount.sh
Can be configured system global defaults in in device.json/remount and refined in run.json/remount
=> unify approach of remount.sh and support profiles (default is default)

bootloader.c, parser/parser_system1.c, signature.c
Fix memory allocations for several assignments
=> Fix memory size allocations

logserver/logserver.c, logserver/logserver_utils.c, logserver/logserver_utils.h
Adds function to send logs formatted to stdout when logserver is not running
=> Fixes stdout log messages when logserver is not running

logserver/logserver.c
=> Removes redundant check

atom.mk, skel/etc/resolv.conf
Right now we ship a default /etc/resolv.conf this way. More in future
=> add skel/directory; and add all files recursively from it in atom.mk

atom.mk, gen_version.sh
=> make gen_version.sh produce sensible output for CMAKE and PVALCHEMY

ctrl.c
According to curl documentation in https://everything.curl.dev/http/post/expect100, the HTTP client might not expect a 100 continue message for the PUT and POST requests if the body length does not exceed a threshold. Our only POST supported requests are signals and commands, so it is ok if we do not return a 100 for all cases. In PUT though, we have some requests that might or might not need a 100.
This patch checks if the "Expected: 100-continue" header is found in a PUT requests and will return or not the 100 confirmation accordingly.
Example of small request that does not expect a 100:
```
*   Trying /var/run/pv-ctrl.pantavisor:0...
* Connected to localhost (/var/run/pv-ctrl.pantavisor) port 80 (#0)
> PUT /steps/locals/test HTTP/1.1
> Host: localhost
> User-Agent: curl/8.1.2
> Accept: …
```
=> fix: pv-ctrl returning 100 continue when client is not expecting it

ctrl.c
This was found using the pvcontrol steps put with a bad name, which in some cases was returning:
```
*   Trying /var/run/pv-ctrl.pantavisor:0...
* Connected to localhost (/var/run/pv-ctrl.pantavisor) port 80 (#0)
> PUT /steps/test HTTP/1.1
> Host: localhost
> User-Agent: curl/8.1.2
> Accept: */*
> Content-Length: 4588
>
} [4588 bytes data]
* We are completely uploaded and fine
* Empty reply from server
* Closing connection 0
```
This has been fixed by flushing every pending to read byte in case we have to return an error in PUT or POST before reading the request body.
=> fix: pv-ctrl empty reply 

init.c, logserver/logserver.c, pantavisor.c, platforms.c, wdt.c, wdt.h
https://www.kernel.org/doc/Documentation/watchdog/watchdog-api.txt
=> fix: close wdt correctly in startup mode

config.c, config.h, parser/parser_system1.c
- drop bootloader.dtb and bootloader.overlay that are not used
=> change drivers overlay feature to use bootloader.fitconfig key

apparmor.c, apparmor.h, atom.mk, config.c, config.h, init.c, init.h
Adds `system.load_lxc_profiles` to load lxc profiles for apparmor
=> Adds config key to load lxc apparmor profiles

pantahub.c
This PR changes the behavior of Pantavisor in case of "could not auth" after a HTTP request. This error message is shown when the client waiting for a reply times out. In this case, the idea is to reset the connection, going back to Pantavisor trying to get the token from the server.
This will make us evaluate again if we should rollback during TESTING, as we weren't doing that anymore once a token is retrieved and thus not checking again if connection was lost.
=> fix: unstable connection with Hub does not trigger a rollback when TESTING

plugins/pv_lxc.c
Also: Improve pv_start_container to return distinguished return codes on error of child process.
=> use lxc 'inlay' approach rather than bindmounts to implement config overlays

updater.c
Traditionally, the count to make the config key revision.retries work was stored in memory and sent to hub only in the progress JSON in case of QUEUED and DOWNLOADING. This would make reboots across updates work just in those cases, leaving INPROGRESS out.
Furthermore, if Pantavisor found an INPROGRESS revision, it would end up in an infinite loop, as it was considering it as a wrong revision but not setting it as an ERROR one in hub.
With this patch, we send the retry count in every progress JSON and start resuming revisions in hub that are INPROGRESS. That way, INPROGRESS revisions can take advantage of the retry system.
=> fix: INPROGRESS revisions in hub entering updater into loop

blkid.c
Fixes the volume detection on ubifs file system
The previous code got the number of volumes (N) and iterated from 0 to N -1 looking for the volume set as root in the configuration. This new implementation gets all the volumes and checks to see if any of them have the name set to root.
=> Fixes ubifs volume detection

signature.c
A new filtering mechanism for secureboot that allows to limit the signatures that can be validated using OEM keys:
* The pvs included/excluded code has been reused to accept the same syntax for making components non OEM-signable.
* The default value is [ "bsp/\*\*" ], or [ "bsp/\*\*", "$PV_OEM_NAME/**" ] when PV_OEM_NAME is defined in config.
* If any of the forbidden artifacts is found included in a sig file, the file will be validated with the default keys, even if its [CN name is PV_OEM_NAME](https://docs.pantahub.com/storage/#certificate-chain-of-trust).
=> set a mechanism to avoid validating bsp and OEM config using OEM certs

CMakeLists.txt, gen_version.sh
* support PANTAVISOR_DISTRO_VERSION define for cmake
* support PANTAVISOR_DISTRO_NAME define for cmake
=> Introduce option to inject distro version and name into pantavisor version.c

ctrl.c
Currently, pv-ctrl do not return the `Content-Length` of the response body, while this is not mandatory in HTTP/1.1 is necessary for compatibility with HTTP/1.0 or for not "chunked encoding" response (`Transfer-Encoding: chunked`) so right now we are sending a not standard response/
=> fix: add content-length to OK responses when necessary

CMakeLists.txt, pvtx/pvtx.c, pvtx/pvtx_ctrl.c, pvtx/pvtx_state.c, pvtx/pvtx_txn.c, pvtx/pvtx_utils/base64.c, pvtx/pvtx_utils/base64.h, pvtx/pvtx_utils/sha256-internal.c, pvtx/pvtx_utils/sha256_i.h
Fix some rough edges in pvtx
* Remove some debug prints
* Fix bugs linking bsp under specific circumstances
* Fix deploy behaviour to match with the old pvtx script
=> Fix pvtx command

scripts/pvcrash
pvcrash always exited with error and couldn't be used.
=> Fix pvcrash

pvtx/pvtx.c
Improve help command adding missing features
=> Improve pvtx help command

scripts/volmount/verity/dm, volumes.c
fix: fixed flip on volume mount
fix: fixed error reporting on mount and umount
=> fix: correct missing traildir on dm script
